
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes


homeassistant:
  external_url: 'https://funhome.eggorkiwi.eu:10520'
  internal_url: 'http://192.168.15.107:8123'

# Internal HTTP only
http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.20.0.3

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

light:
  - platform: group
    name: Ljus Vardagsrum
    unique_id: ljus_vardagsrum_group
    entities:
      - light.0x08fd52fffe4bccc6
      - light.0x08fd52fffe3357fe

input_boolean:
  motion_lights_active:
    name: Motion Lights Active
    initial: off